/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getUpdateToolsSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-update-tools',
    description: '更新全局 OpenSpec 工具链 - 构建 red-cli 和 openspec-cn，并刷新全局 skills 与 commands。',
    instructions: getUpdateToolsInstructions(),
    license: 'MIT',
    compatibility: '需要本地 ai_tool_collection 仓库、PowerShell、pnpm、Go/构建 red-cli 所需环境。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

function getUpdateToolsInstructions(): string {
  return `更新全局 OpenSpec 工具链。该流程只处理全局安装与全局 AI 工具配置，不读取或修改 Redmine 账号配置，也不依赖当前项目路径。

---

## 目标

运行 ai_tool_collection 中的全局更新脚本，完成：

1. 构建或刷新 \`red-cli\`
2. 构建或刷新 \`openspec-cn\`
3. 更新 \`~/.openspec-cn/bin\` 中的命令 shim
4. 刷新 Codex 与 Claude 的全局 OpenSpec skills 和 slash commands

---

## 关键原则

- 使用用户全局目录（默认 \`$HOME\`）作为目标，不要求当前目录是 OpenSpec 项目。
- 不运行 \`openspec-cn redmine setup/test/current\`，不检查 Redmine token、实例、项目 ID 或本地项目映射。
- 不要求当前工作区存在 \`openspec/\`，因为工具配置是全局的。
- 如果需要更新生成的 skill/command，使用全局路径，默认目标是 \`$HOME\`。
- 默认只支持并刷新 \`codex\` 与 \`claude\` 两个 AI 工具；不要因为检测到其他工具目录就更新其他工具。

---

## 定位脚本

按顺序寻找更新脚本：

1. 当前工作区的 \`update-global-openspec-tools.ps1\`
2. \`G:\\tools\\ai_tool_collection\\update-global-openspec-tools.ps1\`
3. 用户提供的 ai_tool_collection 路径下的 \`update-global-openspec-tools.ps1\`

如果找不到脚本，停止并说明需要 ai_tool_collection 路径。

---

## 执行

在 Windows PowerShell 中运行：

\`\`\`powershell
powershell -NoProfile -ExecutionPolicy Bypass -File "<script-path>"
\`\`\`

可选参数：

- \`-Force\`: 强制刷新已安装的 skills 和 commands
- \`-Tools "codex,claude"\`: 选择要刷新的 AI 工具；默认固定为 Codex 和 Claude
- \`-SkipOpenSpecBuild\`: 跳过 openspec-cn 构建
- \`-SkipRedCliBuild\`: 跳过 red-cli 构建
- \`-SkipArtifactUpdate\`: 只更新可执行命令，不刷新 AI skills/commands
- \`-Watch\`: 监听源码变化后自动更新

默认应直接运行不带参数的脚本；只有用户明确要求时才添加可选参数。不要把 \`-Tools\` 改为其他工具集合，除非用户明确要求。

脚本内部会使用 \`openspec-cn init "$HOME" --tools codex,claude --profile core --force\` 刷新全局 artifacts，确保 \`/opsx:update-tools\` 和 \`openspec-update-tools\` 会出现在 Codex 与 Claude 中，即使用户已有旧的全局工作流配置。

---

## 验证

脚本完成后运行：

\`\`\`powershell
openspec-cn --version
red-cli --version
Get-Command openspec-cn
Get-Command red-cli
\`\`\`

如需确认 Codex 与 Claude 的全局命令已刷新，可检查：

\`\`\`powershell
Test-Path "$HOME\\.codex\\prompts\\opsx-update-tools.md"
Test-Path "$HOME\\.codex\\skills\\openspec-update-tools\\SKILL.md"
Test-Path "$HOME\\.claude\\commands\\opsx\\update-tools.md"
Test-Path "$HOME\\.claude\\skills\\openspec-update-tools\\SKILL.md"
Test-Path "$HOME\\.openspec-cn\\bin\\openspec-cn.cmd"
Test-Path "$HOME\\.openspec-cn\\bin\\red-cli.cmd"
\`\`\`

---

## 输出要求

完成后简要报告：

- 使用的脚本路径
- openspec-cn 与 red-cli 是否可执行
- 全局 skills/commands 是否已刷新
- 如果某一步失败，给出失败命令和错误摘要

不要要求用户配置 Redmine，也不要把当前项目路径作为必要前提。`;
}

export function getOpsxUpdateToolsCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Update Tools',
    description: '更新全局 red-cli、openspec-cn 以及 OpenSpec skills/commands',
    category: 'Maintenance',
    tags: ['workflow', 'tools', 'update', 'global'],
    content: getUpdateToolsInstructions(),
  };
}
